export const GET_MY_GDPR_PERMISSION = 'GetMyGDPR';
export const GET_OTHER_GDPR_PERMISSION = 'GetOtherGDPR';
export const DELETE_MY_GDPR_PERMISSION = 'DeleteMyGDPR';
export const DELETE_OTHER_GDPR_PERMISSION = 'DeleteOtherGDPR';

export const GDPRPermissions = [
  GET_MY_GDPR_PERMISSION,
  GET_OTHER_GDPR_PERMISSION,

  DELETE_MY_GDPR_PERMISSION,
  DELETE_OTHER_GDPR_PERMISSION,
];
